In [4]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import scipy.linalg

#### Задание 1

Решите линейную систему:

In [2]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([2, 5, 1])
np.linalg.solve(A, B)

array([-0.9       , -0.7       ,  1.43333333])

In [3]:
A1 = np.linalg.inv(A)
print(A1)
print('det=', np.linalg.det(A))
np.dot(A1, B)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]
det= 59.999999999999986


array([-0.9       , -0.7       ,  1.43333333])

#### Задание 2 

Найти псевдорешение системы:

In [6]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

#### Задание 3 

Сколько решений имеет линейная система:

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[2, 5, 1]])
C = np.concatenate((A, B.T), axis=1)
print(C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[1 2 3 2]
 [4 5 6 5]
 [7 8 9 1]]


(2, 3)

Система не имеет решений, так как ранг расширенной матрицы больше ранга исходной.

In [9]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([[2, 5, 1]])
C = np.concatenate((A, B.T), axis=1)
print(C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[1 2 3 2]
 [4 0 6 5]
 [7 8 9 1]]


(3, 3)

Теперь ранги равны и система имеет решения.

#### Задание 4

Вычислите LU-разложение матрицы:
После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [6]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(P)
print("")
print(L)
print("")
print(U)

B = np.array([3, 5, 31])
np.linalg.solve(A, B)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]

[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


array([ 2.87962963, -0.80092593,  0.57407407])

#### Задание 5

Найдите нормальное псевдорешение недоопределенной системы:

In [ ]:
def Q(x, y):
    return(x**2 + y**2 + z**2)

Как сделать функцию Q понятно, а вот как дальше с помощью нее найти минимум с тремя переменными я не поняла. 

In [8]:
A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([1, 12])
np.linalg.lstsq(A, B)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

#### Задание 6

Найдите одно из псевдорешений вырожденной системы:

In [9]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)

print(A)
print('')
print(Q)
print('')
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]

[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.77635684e-15]]


In [10]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [11]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  8.43769499e-15])

In [12]:
X1 = np.linalg.solve(R1, B1)
X1

array([1.50000000e+00, 9.32822279e-15])

In [13]:
X = np.append(X1, 0)
print(X)
np.linalg.norm(X)

[1.50000000e+00 9.32822279e-15 0.00000000e+00]


1.4999999999999896

In [14]:
np.linalg.norm(np.dot(A, X) - B)

1.2247448713915894

Попробуйте также отыскать и нормальное псевдорешение.

In [18]:
np.linalg.lstsq(A, B)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([ 1.25,  0.5 , -0.25]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 1.47280825e-16]))

In [20]:
X = np.array([1.25, 0.5, -0.25])
np.linalg.norm(X), np.linalg.norm(np.dot(A, X) - B)

(1.3693063937629153, 1.224744871391589)